# Generated by Django 4.0.3 on 2022-04-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
